### ISSUE TITLE
Removing from entities

### ISSUE THREAD

**Issue by DriesS** [barrystaes/react-trebuchet#13]
Hi,

I'm using the test-bottlesapi-apimiddleware application to help writing my own application. Now I see you didn't implement a delete method for the reducer of entities. What would be a good approach to remove the item from the store on a successful api call of type delete?

[Link to file](https://github.com/barrystaes/react-slingshot/blob/test-bottlesapi-apimiddleware/src/reducers/entities.js#L14)

**Comment by barrystaes** [comment]
Correct, i havent implemented that since i wasn't sure about the "right" design myself until recently.
Also note that branch is experimental, notably the latest commit. :8ball:

Afaik, the right approach here would be to [not actually delete items from entities](https://github.com/reactjs/redux/issues/386). What you can do is add a `isDeleted` flag, or remove the ID from an array. If you have the schema's right, normalizr returns nice arrays in the `action.payload.result` value.

**Comment by barrystaes** [comment]
Answered long time ago, closing now since repository is being archived.
